name: Render
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: rnd_7On3sUgyUMwMgxfJEokh89opfIKJ
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 20
          wait: 16000
          sleep: 30000